### ISSUE TITLE
ArchLinux can now be installed from the AUR

### ISSUE THREAD

**Issue by Hill-98** [mame/wsl2-ssh-agent#5]
Hi, I really like this project that allows me to use 1Password for Windows as an ssh agent for WSL.

I created an ArchLinux AUR package for it: <https://aur.archlinux.org/packages/wsl2-ssh-agent>

Can you add installation instructions for it in README.md?

**Comment by mame** [comment]
Could you send a PR to insert a new section "How to use (for ArchLinux)" between the current "How to use" and "Troubleshooting" sections?
