### ISSUE TITLE
Add options for custom exe paths and extension messages

### ISSUE THREAD

**Issue by Hill-98** [mame/wsl2-ssh-agent#6]
If `appendWindowsPath = false`, then wsl2-ssh-agent will fail to start, you can add options to allow custom ·ssh.exe· and `powershell.exe` paths.

If the Windows ssh-agent is manually upgraded to OpenSSH 8.9+, or a different SSH Agent implementation is used, extended messages are available and we can add options to control it.

**Comment by mame** [comment]
I think it's good to have. Is the following strategy good?

- If a user explicitly gives a command-line option (e.g., `-ssh-command /path/to/ssh.exe` or `-powershell-command /path/to/powershell.exe`), use it.
- If not given, look for `ssh.exe` in the PATH. If not found, check if `/mnt/c/Windows/System32/OpenSSH/ssh.exe` and `/mnt/c/Windows/System32/WindowsPowerShell/v1.0/PowerShell.exe"` are available.

It would be great if you could send me a PR. Or, I'll probably do it myself a little later.
