### ISSUE TITLE
New implementation based on Shell

### ISSUE THREAD

**Issue by Hill-98** [mame/wsl2-ssh-agent#9]
After #7, I've been thinking about moving away from using PowerShell as a bridge because the input/output doesn't seem that reliable.

So with this new Shell-based implementation, its core uses SSH agent forwarding, which should be more stable and efficient.

I'm not sure what effect it has on the speed of WSL startup, so can you test it for me?

Here: <https://github.com/Hill-98/wsl2-ssh-agent-shell>

**Comment by Hill-98** [comment]
I want to execute it under Windows, observe whether WSL is started through Windows events, and then run SSH agent forwarding. But there seemed to be no WSL related events for Windows, so I had to give up this idea.

**Comment by Hill-98** [comment]
However, it does not implement extended message filtering. If there is no problem, can extended message filtering be implemented in this project?

**Comment by mame** [comment]
At first, I am reasonably satisfied with the current wsl2-ssh-agent. I am happy to introduce a change that would help those who is using `appendWindowsPath = false`, but I don't have the motivation for anything more than that.

I designed wsl2-ssh-agent in mind of user experience that "downloads a binary, adds one line to the .bashrc, and works nice". It seems that the basic policy is different from your project. (I do never deny yours, but TBH I don't like to use it.)

I am technically interested in the idea of doing the ssh.exe version check in repeater.ps1 that came up in the discussion #7 with you. If you are not interested in that, I will give it a try later.

**Comment by Hill-98** [comment]
Well, if you don't want to implement a bridge in the form of SSH agent forwarding, I would refactor Repeater.ps1 to add ssh-agent.exe version checking and extended message filtering to it.
